version: '2.1'
services:
  master:
    image: hunsche/pg-master
    volumes:
      - master_data:/var/lib/postgresql/data
    ports: 
      - '5532:5432'
    healthcheck: 
      test: psql beers_db -c "\q" && echo ok
      interval: 5s
      retries: 3

  slave:
    image: hunsche/pg-slave
    links:
      - master:master
    ports: 
      - '5432'
    depends_on:
      master:
        condition: service_healthy
      
volumes:
  master_data: