version: '2.1'
services:
  master:
    image: replicant
    volumes:
      - master_data:/var/lib/postgresql/data
    ports: 
      - '5432:5432'

  slave:
    image: replicant
    links:
      - master:master
    ports: 
      - '5433:5432'

volumes:
  master_data: