version: '2.1'
services:
  master:
    image: hunsche/pg-master
    volumes:
      - master_data:/var/lib/postgresql/data
    ports: 
      - '5532:5432'
    healthcheck: 
      test: psql beers_db -c "\q" && echo ok
      interval: 5s
      retries: 3

volumes:
  master_data: